number1=input("please type an integer and press enter: ")
number2=input("please type another integer and press enter:")
number1=int(number1)
number2=int(number2)
print("number1+number2=",number1+number2)